---
# Cac host duoc quan ly
- hosts: wordpress
  become: yes
  remote_user: root
  vars:
# Ten db wordpress
    wp_mysql_db: wordpress
# Ten user wordpress
    wp_mysql_user: wpuser
# Password cho user
    wp_mysql_password: 
  tasks:
  - name: Install elpel-realease
    yum:
      name: '{{item}}'
      state: present
    with_items:
    - epel-release
    - yum-utils
    - MySQL-python
    - wget

  - name: Update respotory
    yum:
      name: '{{item}}'
      state: present
    with_items:
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm

  - name: config remi
    command: yum-config-manager --enable remi-php73

  - name : install httpd
    yum:
      name: httpd
      state: present

  - name: update sys
    yum:
      name: '*'
      state: latest

  - name: install PHP
    yum: 
      name: '{{item}}'
      state: present
    with_items: 
    - php
    - php-cli
    - php-common
    - php-mcrypt
    - php-gd
    - php-json
    - php-curl
    - php-mbstring
    - php-mysqlnd
    - php-xml
    - php-xmlrpc
    - php-opcache

  - name: Start httpd service
    service: 
      name: httpd
      enabled: true
      state: started

  - name: Install Mysql
    yum:
      name: '{{item}}'
      state: present
    with_items:
    - mariadb
    - mariadb-server

  - name: Start Mysql Service
    service: 
      name: mariadb
      enabled: true
      state: started

  - name: Deletes anonymous MySQL server user for localhost
    mysql_user: user="" state="absent"

  - name: create db wordpress
    mysql_db:
      name: "{{wp_mysql_db}}"
      encoding: latin1
      collation: latin1_general_ci

  - name: create user wpress
    mysql_user:
      name: "{{wp_mysql_user}}"
      host: "%"
      password: "{{wp_mysql_password}}"
      priv: "*.*:ALL"

  - name: download source wordpress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /var/www/html
      remote_src: yes

  - name: mv src wordpress
    shell: mv /var/www/html/wordpress/* /var/www/html/

  - name: mv file config
    shell: mv /var/www/html/wp-config-sample.php /var/www/html/wp-config.php

  - name: update file config wordpress
    lineinfile: dest=/var/www/html/wp-config.php regexp={{ item.regexp }} line={{ item.line }}
    with_items:
    - {'regexp': "define\\( 'DB_NAME', '(database_name_here)+' \\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
    - {'regexp': "define\\( 'DB_USER', '(username_here)+' \\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
    - {'regexp': "define\\( 'DB_PASSWORD', '(password_here)+' \\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_password}}');"}

  - name: chmod apache
    shell: '{{item}}'
    with_items:
    - chown -R apache:apache /var/www/html/*
    - chmod -R 755 /var/www/html/*
...